# Generated by Django 4.2.11 on 2024-03-17 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rabbitimage',
            old_name='rabbit',
            new_name='rabbit_group',
        ),
    ]
