# Generated by Django 4.2.11 on 2024-03-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0002_rename_rabbit_rabbitimage_rabbit_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabbit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rabbit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rabbitimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rabbitimage',
            name='updated_at',
        ),
    ]
