# Generated by Django 4.2.11 on 2024-03-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0003_remove_rabbit_created_at_remove_rabbit_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Doe (Female)'), ('M', 'Buck (Male)')], max_length=1),
        ),
    ]
