# Generated by Django 4.2.11 on 2024-03-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabbits', '0004_rabbit_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rabbits', to='rabbits.rabbitgroup'),
        ),
        migrations.AlterField(
            model_name='rabbitimage',
            name='rabbit_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rabbits.rabbitgroup'),
        ),
    ]
